enabled: true
play-sound: true
sound-name: 'ENTITY_VILLAGER_DEATH'
sound-name-wandering-trader: 'ENTITY_WANDERING_TRADER_DEATH'

# use 0 for unlimited radius
max-broadcast-radius: 0
# if you're traded with a villager previously then you will get notified
# note this is only compatible on Paper servers
only-broadcast-if-traded-with: false
# optionally limit broadcasts to specific worlds
broadcast-worlds: ['*']
# only broadcasts if they were formally normal villagers
broadcast-zombie-villager-deaths: true
# villagerannouncer.receive-broadcasts
players-require-premissions: false
# if DiscordSRV is installed then send any messages to the main text channel
discordsrv-send-message-to-main-channel: true
# this is only applicable if you have world filtering
# or are using player permisisons
log-messages-to-console: true

include-wandering-trader: false

# messages are formatted with MiniMessage
# for information go to https://docs.advntr.dev/minimessage/format.html
messages:
  # all four of these settings will populate the %villager% variable:
  villager: 'villager'
  baby-villager: 'baby villager'
  zombie-villager: 'zombie villager'
  baby-zombie-villager: 'baby zombie villager'
  wandering-trader: 'wandering trader'

  # populates %location% variable:
  location: '<reset>( <color:gold>XYZ: %x% %y% %z%, <color:yellow>in <color:green>%world-name%</color>)'
  # if you want a clickable link with a URL, use the example below:
  #location: '<reset><click:OPEN_URL:http://mymapsite.com/world=%world-name%;%x%,%y%,%z%>( <color:gold>XYZ: %x% %y% %z%, <color:yellow>in <color:green>%world-name%</color>)</click>'

  villager-message-with-profession: '<color:yellow>A %villager% has died! Profession: %villager-profession%, level: %villager-level% %location%'
  villager-message: '<color:yellow>A %villager% has died! %location%'
  villager-infection-with-profession: '<color:yellow>A %villager% has been infected by %entity%! Profession: %villager-profession%, level: %villager-level% %location%'
  villager-infection: '<color:yellow>A %villager% has been infected by %entity%! %location%'
  death-by-entity: '<color:yellow>A %villager% was killed by %entity% %location%'
  death-by-misc: '<color:yellow>A %villager% died by %death-cause% %location%'

  wandering-trader-death: '<color:yellow>A %wandering-trader% has died! %location%'
  wandering-trader-death-by-entity: '<color:yellow>A %wandering-trader% was brutally murdered by <color:red>%entity%<color:yellow>! %location%'

# Available variables:
# %villager%
# %player%
# %entity%
# %entity-type%
# %death-cause%
# %world-name%
# %world-type%
# %villager-profession%
# %villager-level%
# %villager-experience%
# %villager-type%

file-version: 6